# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/default'
        # Storage para el PDF adjunto de entrada del flujo ChatToolPdf
        chattoolpdf.storage.attach_pdf:
            adapter: 'aws'
            options:
                client: 'Aws\S3\S3Client'
                bucket: '%env(MINIO_BUCKET_CHATTOOLPDF_ATTACH_PDF)%'
                prefix: ''

        # Storage para el ZIP generado por el flujo ChatToolPdf
        chattoolpdf.storage.zip:
            adapter: 'aws'
            options:
                client: 'Aws\S3\S3Client'
                bucket: '%env(MINIO_BUCKET_CHATTOOLPDF_ZIP)%'
                prefix: ''

        canvas.storage.images:
            adapter: 'aws'
            options:
                client: 'Aws\S3\S3Client'
                bucket: '%env(MINIO_BUCKET_CANVAS_IMAGE)%'
                prefix: ''
