framework:
    messenger:
        transports:
            async_project_ia: '%env(MESSENGER_TRANSPORT_DSN)%_async_project_ia?stream=async'
            async_asitente_api_ia: '%env(MESSENGER_TRANSPORT_DSN)%_async_asitente_api_ia?stream=async'
        routing:
            'OSP\Message\AsistenteIA\WorkerProjectMessageInterface': async_project_ia